FROM alpine:latest as original
RUN apk -U add \
  atuin \
  delta \
  eza \
  fd \
  fish \
  less \
  rclone \
  ripgrep \
  starship \
  zoxide \
  zsh

FROM alpine:latest as sandboxed
RUN apk -U add \
  bubblewrap \
  bash \
  coreutils \
  squashfs-tools btrfs-progs e2fsprogs e2fsprogs-extra
COPY --from=original /bin /tmp/original/bin
COPY --from=original /etc /tmp/original/etc
COPY --from=original /lib /tmp/original/lib
COPY --from=original /sbin /tmp/original/sbin
COPY --from=original /usr /tmp/original/usr
COPY flatwrap.sh bake.sh .
RUN \
  OS="_any" ARCH="" RELOAD="0" KEEP="1" \
  ./flatwrap.sh /tmp/original bluefin-cli \
    /usr/bin/atuin \
    /usr/bin/delta \
    /usr/bin/eza \
    /usr/bin/fd \
    /usr/bin/fish \
    /usr/bin/rclone \
    /usr/bin/rg \
    /usr/bin/starship \
    /usr/bin/zoxide \
    /bin/zsh:/usr/bin/zsh

FROM scratch
COPY --from=sandboxed bluefin-cli/usr /usr
COPY extension-release-any /usr/lib/extension-release.d/extension-release.bluefin-cli
