name: build-systemd-sysexts
on:
  schedule:
    - cron: '0 8,20 * * *'  # 8am and 8pm every day
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'sysext-bakery/**'
      - '!sysext-bakery/README.md'
      - '!sysext-bakery/**/README.md'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/*'
      - 'sysext-bakery/**'
      - '!sysext-bakery/README.md'
      - '!sysext-bakery/**/README.md'
  merge_group:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      # allow the action to create a release
      contents: write
    steps:
      # checkout the sources
      - uses: actions/checkout@v4

      # prepare build host
      - name: install prerequisites
        run: |
          set -euxo pipefail

          sudo apt update -qq && sudo apt install -yqq \
            curl \
            jq \
            squashfs-tools \
            xz-utils \
            gawk

      - name: build release artifacts
        working-directory: ./sysext-bakery
        run: |
          ./build.sh

      - name: Upload system extension raw images
        uses: actions/upload-artifact@v4
        with:
          name: sysext-images
          path: ./sysext-bakery/*.raw
